# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160510_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='websit',
            new_name='website',
        ),
    ]
